dotnet/HttpRepl

LICENSE.txt

This fixes the arcade error that pointed out the license file content wasn't right.

Fixing license file issue

---

src/Microsoft.Repl.Tests/Microsoft.Repl.Tests.csproj
src/Microsoft.Repl.Tests/Mocks/MockCommand.cs
src/Microsoft.Repl.Tests/Mocks/MockConsoleManager.cs
src/Microsoft.Repl.Tests/Mocks/MockWritable.cs
src/Microsoft.Repl.Tests/ShellTests.cs

Added tests for below key press events:
- Enter
- Tab 
- Shift + Tab
- Control + U
- Left Arrow
- Ctrl + Left Arrow
- Right Arrow
- Ctrl + Right Arrow
- Home
- Ctrl + A
- End
- Ctrl + E

Added tests for remaining handled key press events

---

src/Microsoft.HttpRepl.Tests/HttpStateTests.cs
src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs
src/Microsoft.HttpRepl/Commands/RunCommand.cs
src/Microsoft.HttpRepl/HttpState.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx

The `GetEffectivePath` overloads had some bugs and some unreachable code, so there's a decent amount of refactoring in addition to the tests.
Also fixes #76 since that was along the same code path for testing and whatnot.

Additional tests for HttpState, along with some bug fixes and refactoring

---

src/Microsoft.Repl.Tests/ConsoleHandling/AnsiColorExtensionsTests.cs
src/Microsoft.Repl.Tests/DisposableTests.cs
src/Microsoft.Repl.Tests/Parsing/CoreParseResultTests.cs
src/Microsoft.Repl/ConsoleHandling/Point.cs

Adding tests for AnsiColorExtensions, Disposable, Disposable<T> and some of CoreParseResult. Also removing some unused code from the Point class.

Adding some more tests for Microsoft.Repl

---

src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj

In preparation for publishing the package, update the metadata to match Microsoft guidelines and align with other tools.

Update Nuget package metadata

---

src/Microsoft.HttpRepl.Tests/Commands/ExitCommandTests.cs
src/Microsoft.Repl/Commanding/DefaultCommandDispatcher.cs

Changing DefaultCommandDispatcher to not write the prompt if the application is exiting.

---

src/Microsoft.HttpRepl.IntegrationTests/Commands/EchoCommandTests.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/SetBaseCommandTests.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/SetHeaderCommandTests.cs
src/Microsoft.HttpRepl.Tests/Commands/SetBaseCommandTests.cs

Added integration tests for - EchoCommand, SetBaseCommand, SetHeaderCommand

Added integration tests for - EchoCommand, SetBaseCommand, SetHeaderCommand

---

src/Microsoft.HttpRepl.Tests/Commands/RunCommandTests.cs
src/Microsoft.HttpRepl.Tests/Commands/SetBaseCommandTests.cs
src/Microsoft.HttpRepl.Tests/Commands/SetHeaderCommandTests.cs
src/Microsoft.Repl.Tests/ConsoleHandling/AnsiColorExtensionsTests.cs
src/Microsoft.Repl/ConsoleHandling/AnsiColorExtensions.cs

Fixing a colorization issue when user has non-default console colors

---

README.md

- My previous PR placed the opening quote before the flag instead of at the start of the parameter value where it should be.

README.md - Update Installation Command

---

src/Microsoft.HttpRepl/Preferences/WellKnownPreference.cs

No clue why this didn't come across in the previous PR.

Actually removing an errant using.

---

azure-pipelines.yml

Based on guidance from the arcade folks, this change adds stages to our yaml build definition following the instructions [here](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/YamlStagesPublishing.md).

Converting the yaml pipeline to use stages

---

src/Microsoft.HttpRepl.Tests/OpenApi/SchemaDataGeneratorTests.cs
src/Microsoft.HttpRepl/OpenApi/ApiDefinitionReader.cs
src/Microsoft.HttpRepl/OpenApi/Schema.cs
src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs

Fixes #197 
Fixes #198
Creates some additional tests for the example data generation code

Change data generator to generate values for date-time and ignore readonly properties

---

src/Microsoft.Repl/Input/InputManager.cs

This allows keypress combinations like AltGr+7.
Fixes issue #226

Fixes #226

---

src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx
test/Microsoft.HttpRepl.Tests/Commands/PostCommandTests.cs

Fixes #213.
Supersedes PR #229 which I'll closed with a comment once this PR goes in.

Friendlier error message when default editor is not found.

---

src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj

Security vulnerability scanning turned up a reference that needed to be updated. This PR fixes that.

Address security vulnerability

---

eng/Versions.props

With the 3.1 preview almost done baking (and a release/3.1 branch created) and minimal work scheduled for the 3.2 release (we'll branch from release/3.1 for that), we're going to go ahead and update the version in master to 5.0.0-preview so we can start pulling in some of the breaking changes we've got scheduled for that release. That's all this PR does.

Update version to 5.0.0-preview

---

src/Microsoft.Repl/Parsing/CoreParser.cs
test/Microsoft.Repl.Tests/Parsing/CoreParseResultTests.cs

(cherry picked from commit d0a5110233f7827aee93cd350ea43f501577b665) original PR #366

Fix issue with extra spaces in commands

---

global.json

Just updating to the latest preview SDK released today.

Update to .NET 5 Preview 8

---

src/Microsoft.HttpRepl/Telemetry/Events/PreferenceEvent.cs
src/Microsoft.HttpRepl/Telemetry/Events/SetHeaderEvent.cs
test/Microsoft.HttpRepl.Tests/Telemetry/Events/PreferenceEventTests.cs
test/Microsoft.HttpRepl.Tests/Telemetry/Events/SetHeaderEventTests.cs

Avoid exceptions in command-specific telemetry events

---

src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx

Resolves #422 and a few other similar places.

Fix incorrect error messages

---

TELEMETRY.md
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx

Changing the telemetry welcome message to better match the .NET CLI message and to include links for more information.

Updating telemetry welcome message

---

eng/Versions.props

Part of prep for release of 5.0

Update HttpRepl version to 5.1

---

eng/Versions.props

Update version to 5.0.1

---

src/Microsoft.HttpRepl/ApiConnection.cs
src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs
src/Microsoft.HttpRepl/Commands/ConnectCommand.cs
src/Microsoft.HttpRepl/Commands/ListCommand.cs
src/Microsoft.HttpRepl/HttpState.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx
test/Microsoft.HttpRepl.Tests/Commands/ConnectCommandTests.cs

Clear state on connect

---

azure-pipelines.yml

Per https://github.com/dotnet/arcade/issues/9592.

Switch to new build images

---

src/Microsoft.HttpRepl/Commands/HelpCommand.cs
src/Microsoft.HttpRepl/Commands/SetQueryParamCommand.cs
src/Microsoft.HttpRepl/HttpState.cs
src/Microsoft.HttpRepl/Program.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx
src/Microsoft.HttpRepl/Telemetry/Events/SetQueryParamEvent.cs
src/Microsoft.HttpRepl/Telemetry/TelemetryConstants.cs
test/Microsoft.HttpRepl.IntegrationTests/SampleApi/SampleApiServer.cs
test/Microsoft.HttpRepl.Tests/Commands/SetQueryParamCommandTests.cs
test/Microsoft.HttpRepl.Tests/HttpStateTests.cs

This PR is based on #448 by @ygalbel but because I let that PR go so stale, it was difficult to rebase and rework it. I've included the suggestions on the PR from @atifaziz in terms of the naming and url encoding, I added another test and fixed some things that broke locally in the integration tests.

Add set query-param command

---

src/Microsoft.HttpRepl.Telemetry/Microsoft.HttpRepl.Telemetry.csproj
src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj
src/Microsoft.Repl/Microsoft.Repl.csproj

Updates the 3 /src projects to include a .NET 8 build in prep for .NET 8 GA coming soon

Add .NET 8 build

---

azure-pipelines.yml

This is step 3 of the template migration. There will likely be more tweaks, but this is the real switchover.

Template migration

---

NOTICE.txt
src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj

Adds a NOTICE.txt for open source software that we ship as part of the nuget package.

Add NOTICE.txt to shipping nuget packages
