dotnet/HttpRepl

azure-pipelines.yml

That was left over from the build definition we pulled in from the AspLabs repo.

Removing node step from build definition

---

src/Microsoft.HttpRepl/Commands/ChangeDirectoryCommand.cs

Fixes #29 - The error in the code that displayed the metadata for a particular endpoint after the cd was successful. That doesn't work when there's no directory structure. Not doing it has no negative impact on future commands, though.

Changing the ChangeDirectoryCommand so it won't throw an NRE when there's no directory structure available.

---

src/Microsoft.HttpRepl/Commands/SetHeaderCommand.cs

Fixes #34 - GetHelpDetails is used in a way that requires the callee to make sure it should actually respond. SetHeaderCommand did not do that, so it responded when the help request was actually for a command that came later in the list - SetSwaggerCommand, for instance.

Fixes SetHeader command to not blindly return documentation on GetHelpDetails

---

src/Microsoft.HttpRepl/Program.cs

The `Program` class' `Start` method includes code that checks for `-h`. This PR lists `-h` as a shorthand option alternative to `--help`.

List -h as an alias to the --help option

---

src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs

This is a small fix for something I noticed while writing the doc. The generic dictionary used for storing HTTP request headers should be created as case-insensitive (as most others in the code base are). Without that change, the first condition in the following if statement is problematic:
https://github.com/aspnet/HttpRepl/blob/e261002df7f7d96f26337b2057b6e3f31dfe88da/src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs#L128
Imagine a situation in which I execute the following command:
```console
https://localhost:5001/People~ post -h Content-Type=application/json
```
The HTTP request header uses a different casing than what the if statement is expecting. With a case-insensitive dictionary, the casing in this situation no longer matters.

Initialize HTTP request headers Dictionary as case-insensitive

---

src/Microsoft.HttpRepl/Commands/ChangeDirectoryCommand.cs
src/Microsoft.HttpRepl/Commands/ClearCommand.cs
src/Microsoft.HttpRepl/Commands/CommandDispatcherExtensions.cs
src/Microsoft.HttpRepl/Commands/EchoCommand.cs
src/Microsoft.HttpRepl/Commands/ExitCommand.cs
src/Microsoft.HttpRepl/Commands/HelpCommand.cs
src/Microsoft.HttpRepl/Commands/ListCommand.cs
src/Microsoft.HttpRepl/Commands/RunCommand.cs
src/Microsoft.HttpRepl/Commands/SetBaseCommand.cs
src/Microsoft.HttpRepl/Commands/SetHeaderCommand.cs
src/Microsoft.HttpRepl/Commands/SetSwaggerCommand.cs
src/Microsoft.HttpRepl/Commands/UICommand.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx

This is a replacement PR for #48 to fix #43. 
`HelpCommand.GetCoreHelp(...)` had all of the help summaries hard-coded. This PR changes it to use the ICommand.GetHelpSummary(...) for each command. It also moves the strings used for GetHelpSummary into Resources.

Using ICommand.GetHelpSummary from the HelpCommand

---

src/Microsoft.HttpRepl.IntegrationTests/BaseIntegrationTest.cs
src/Microsoft.HttpRepl.IntegrationTests/NonSwaggerIntegrationTests.cs
src/Microsoft.HttpRepl.IntegrationTests/SampleApi/SampleApiServer.cs
src/Microsoft.HttpRepl.IntegrationTests/SampleApi/SampleApiServerConfig.cs

This adds a flag to the test fixture to toggle whether the Swagger
endpoint is active, which allows tests to be written with it on or off.
Still to do: find a way to toggle it on each test run.  Ideally, we
would have a single Theory test which would take as inputs whether the
Swagger endpoint is active, and the corresponding expected output.
Currently the tests have to be separate because the server is started
during Fixture initialization, which is before the test method receives
control.

Add an integration test with the Swagger endpoint disabled

---

src/Microsoft.Repl/Input/InputManager.cs

A quick fix for the detection logic for determining if we need to update the TTY settings, addressing part of #15. 
I put in a separate issue https://github.com/aspnet/HttpRepl/issues/72 to track the tests that need to be written against the whole InputManager class, because I didn't want those to block this simple fix getting in.

Change logic for modifying TTY settings on linux so that character duplication does not occur.

---

README.md
src/Microsoft.HttpRepl/Commands/HelpCommand.cs

Fixes https://github.com/aspnet/HttpRepl/issues/59
Add the official doc (hosted on docs.microsoft.com) link to the product help text. This link should help users find more info when the product help text doesn't suffice.

Add doc link to help text

---

src/Microsoft.HttpRepl/Commands/ClearCommand.cs
src/Microsoft.HttpRepl/Commands/HelpCommand.cs
src/Microsoft.HttpRepl/Commands/RunCommand.cs
src/Microsoft.HttpRepl/Commands/SetBaseCommand.cs
src/Microsoft.HttpRepl/Commands/SetHeaderCommand.cs
src/Microsoft.HttpRepl/Commands/SetSwaggerCommand.cs
src/Microsoft.HttpRepl/Commands/UICommand.cs
src/Microsoft.Repl.Tests/Microsoft.Repl.Tests.csproj
src/Microsoft.Repl/Parsing/CoreParseResultExtensions.cs

Fixes #60 by introducing some extension methods for ICoreParseResult.
Originally, there was a lot of code such as:
```C#
bool canHandle = parseResult.Sections.Count == 2 && string.Equals(parseResult.Sections[0], Name, StringComparison.OrdinalIgnoreCase) && string.Equals(parseResult.Sections[1], SubCommand, StringComparison.OrdinalIgnoreCase));
bool canHandle = parseResult.Sections.Count == 2 && string.Equals(parseResult.Sections[0], Name, StringComparison.OrdinalIgnoreCase) && string.Equals(parseResult.Sections[1], SubCommand, StringComparison.OrdinalIgnoreCase));
```
With this PR, those calls could be replaced with:
```C#
bool canHandle = parseResults.ContainsExactly(Name, SubCommand);
bool canHandle = parseResults.ContainsAtLeast(Name, SubCommand);
```
The simple forms of the method use …

Refactor ICoreParseResult section checking

---

build/PackageVersions.targets
src/Microsoft.HttpRepl.Fakes/Microsoft.HttpRepl.Fakes.csproj
src/Microsoft.HttpRepl.IntegrationTests/Microsoft.HttpRepl.IntegrationTests.csproj
src/Microsoft.HttpRepl.Tests/Microsoft.HttpRepl.Tests.csproj
src/Microsoft.Repl.Tests/Microsoft.Repl.Tests.csproj

We are getting warnings about a downstream reference to a known vulnerable component (System.Net.Http v4.3.0). We're not actually using that here, but in order to get rid of the warnings, I'm adding an explicit reference to a newer version that is not vulnerable.

Updating some test packages and adding an explicit reference to latest System.Net.Http to prevent security issues and warnings.

---

src/Microsoft.HttpRepl.IntegrationTests/NonSwaggerIntegrationTests.cs
src/Microsoft.HttpRepl.IntegrationTests/SwaggerIntegrationTests.cs
src/Microsoft.HttpRepl.Tests/OpenApi/OpenApiV3EndpointMetadataReaderTests.cs
src/Microsoft.HttpRepl/OpenApi/OpenApiV3EndpointMetadataReader.cs

As I started doing additional integration tests yesterday, I realized that the V3 metadata reader was not handling most of the GET endpoints in our sample api server. For example, our sample api server includes an `HttpGet` route for `api/values`, but the current output of our swagger integration tests shows that it's not being picked up:
```
[BaseUrl]/api~ ls
.        []
..       []
Values   [post]
```
Digging a little further, it seems that the `ReadMetadata` method on `OpenApiV3EndpointMetadataReader` would only add a request method to the collection if it had a request body. Even before reading the spec, I realized that couldn't be right - `GET` apis aren't going to have a request body. And indeed, in our sample api swagger endpoint, the `GET` apis didn't have `requestBody` …

Addressing issues in OpenApiV3EndpointMetadataReader

---

src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj

This URL points to the ".NET" icon that's used for other Microsoft global tools and packages.

Add a PackageIconUrl for the Nuget package

---

src/Microsoft.HttpRepl.Fakes/NullPreferences.cs
src/Microsoft.HttpRepl.IntegrationTests/BaseIntegrationTest.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/GetCommandTests.cs
src/Microsoft.HttpRepl/Program.cs
src/Microsoft.Repl/ConsoleHandling/AllowedColors.cs
src/Microsoft.Repl/ConsoleHandling/AnsiColorExtensions.cs

This PR follows on from the discussion on https://github.com/aspnet/HttpRepl/pull/106#discussion_r306454633.
It cleans up the integration test output substantially by allowing a `NullPreferences` object to be used.
Unfortunately, due to https://github.com/aspnet/HttpRepl/blob/6ffda0536534c4c9311b0a82eb29402af371817e/src/Microsoft.HttpRepl/HttpState.cs#L21 and https://github.com/aspnet/HttpRepl/blob/6ffda0536534c4c9311b0a82eb29402af371817e/src/Microsoft.HttpRepl/HttpState.cs#L23 the warning and error colors were not blanked out as part of the `NullPreferences` object. So I had to make a change there as well to always return `AllowedColors.None` rather than always returning the passed-in default. It doesn't appear that this change causes any other unintended consequences, but I wanted to …

Remove colors in integration tests

---

build/PackageVersions.targets
src/Microsoft.Repl/Commanding/CommandWithStructuredInputBase.cs
src/Microsoft.Repl/Commanding/DefaultCommandInput.cs
src/Microsoft.Repl/Input/KeyHandlers.cs
src/Microsoft.Repl/Microsoft.Repl.csproj
src/Microsoft.Repl/Suggestions/FileSystemCompletion.cs

In support of recent interest in the underlying Microsoft.Repl library, this PR converts it to a .NET Standard 1.3 library (as opposed to .net core 2.1 and 3.0 libraries) to expand its reach, and set it to generate a nuget package.
I picked 1.3 based on the chart [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) and the fact that .NET Framework 4.6 is the lowest version in mainstream support (I think) listed in that chart. I'm open to suggestions on a different target, though.
The two new package refs were just because of things that weren't natively supported in netstandard1.3, not because of any changes in the library.
I left out the `<PackageProjectUrl>` in `Microsoft.Repl.csproj` since we don't have documentation or a website specifically …

Convert Microsoft.Repl to a .NET Standard library and add pack

---

src/Microsoft.HttpRepl.Fakes/MockHttpMessageHandler.cs
src/Microsoft.HttpRepl.Tests/Commands/CommandTestsBase.cs
src/Microsoft.HttpRepl.Tests/Commands/GetCommandTests.cs
src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs

As a part of this pr:
- Refactored BaseHttpCommand class to make it more readable
- Added couple of tests to verify format behavior based on content type
- I did not find more areas for testing as most of the areas are covered by Commands that implement the abstract methods. Let me know if you have any suggestions around adding more tests

Refactored BaseHttpCommand and added couple of tests to verify format behavior

---

README.md

- Use quotes for the version parameter.
- Without the quotes the install command will fail when running in ZSH with the following Error: `zsh: no matches found: 3.0.0*`

README.md - Update Installation Command

---

src/Microsoft.HttpRepl.Tests/Commands/SetSwaggerCommandTests.cs
src/Microsoft.HttpRepl/Commands/SetSwaggerCommand.cs

- This issue is cause by `Schema.Properties` is null,  when this exception occur, it will set the `Structure` to null.

Fix the exception "NullReferenceException" throw by set swagger command.

---

src/Microsoft.HttpRepl.Tests/HttpStateTests.cs
src/Microsoft.HttpRepl/HttpState.cs
src/Microsoft.HttpRepl/Preferences/WellKnownPreference.cs

This resolves #123. 
Currently, since there's no mechanism to notify other parts of the system when a preference changes, this will require a restart. I put in #165 to address that in the future for this and other settings that it may be useful for.

Allow the user agent header to be set via a preference

---

src/Microsoft.HttpRepl.Tests/Commands/ListCommandTests.cs
src/Microsoft.Repl/Commanding/CommandWithStructuredInputBase.cs

This fixes #135. The actual exception was thrown by the original line 68, but the problem was a little more complex than just fixing that - it shouldn't have even been in that block of code to begin with.

Fixing a crash on suggestions with ls/dir

---

src/Microsoft.HttpRepl.Fakes/MockHttpContent.cs
src/Microsoft.HttpRepl.Tests/Commands/SetSwaggerCommandTests.cs
src/Microsoft.HttpRepl/Commands/SetSwaggerCommand.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx

Fixes #136 by allowing the user to specify either an absolute url (which already worked) or a relative url (relative to the set base address). If no base address is set, only absolute will work, for obvious reasons.

Change set swagger command to allow both relative (to the base address) and absolute urls

---

src/Microsoft.HttpRepl.IntegrationTests/Commands/ListCommandTests.cs
src/Microsoft.HttpRepl.Tests/Commands/ListCommandTests.cs
src/Microsoft.HttpRepl/Commands/ListCommand.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx

Adds warnings for ls/dir commands when there's no base/swagger/structure, so nothing to do.

---

src/Microsoft.HttpRepl.Tests/Commands/EchoCommandTests.cs
src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs

Fixes #196.
For some reason, there was an extra loop outputting the request body after the response marker. This removes that.

Fix BaseHttpCommand to only print the request body once if echo is on

---

src/Microsoft.HttpRepl/Suggestions/HeaderCompletion.cs

The `HeaderCompletion.GetCompletions` method signature has `IEnumerable<string>` as the return type, which is what the `Where` extension method will return. We are currently calling a `ToList` method on top of this `IEnumerable<string>` and returning that from the `GetCompletions` method.  The `ToList()` method call will allocate memory for the new list. It is unnecessary in the case of  `GetCompletions` as the return type of `Where` method call matches with the return type of `GetCompletions`.
I ran benchmarks with both implementations. You can see the code used for benchmarking [here](https://gist.github.com/kshyju/3f8d5777e0d0c34ef173da7c288d82a4)
Here are the numbers
``` ini
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.18362
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 …
```

Removing the unnecessary list allocation

---

src/Microsoft.HttpRepl.IntegrationTests/BaseIntegrationTest.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/EchoCommandTests.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/GetCommandTests.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/ListCommandTests.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/SetBaseCommandTests.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/SetHeaderCommandTests.cs
src/Microsoft.HttpRepl/HttpState.cs

Resolves #195.
Currently, we use the `~` character at the end of the prompt. However:
1. The `~` character is used on some platforms to indicate the home directory
2. The `>` character is more commonly used as the end of a prompt in other shells
So this changes our usage from `~` to `>`

Change the prompt ending to be a > rather than a ~

---

src/Microsoft.HttpRepl.Tests/OpenApi/OpenApiV3ApiDefinitionReaderTests.cs
src/Microsoft.HttpRepl/OpenApi/OpenApiV3ApiDefinitionReader.cs

Fixes #199 so that the V3 API reader understands and records the schema used in a request body.

Fix OpenApiV3ApiDefinitionReader to detect request body schema

---

src/Microsoft.HttpRepl.IntegrationTests/Commands/ChangeDirectoryCommandTests.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/GetCommandTests.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/ListCommandTests.cs
src/Microsoft.HttpRepl.IntegrationTests/Commands/SetHeaderCommandTests.cs
src/Microsoft.HttpRepl.Tests/Commands/ListCommandTests.cs
src/Microsoft.HttpRepl/Commands/ChangeDirectoryCommand.cs
src/Microsoft.HttpRepl/Commands/ListCommand.cs
src/Microsoft.HttpRepl/Extensions/RequestInfoExtensions.cs

Resolves #192 
Since the HTTP spec says verbs are uppercase, we should display them that way. We'll still accept lowercase for the commands

For cd and dir/ls commands, display http verbs in uppercase

---

src/Microsoft.HttpRepl.Tests/Commands/UICommandTests.cs
src/Microsoft.HttpRepl/Commands/UICommand.cs
src/Microsoft.HttpRepl/Preferences/WellKnownPreference.cs
src/Microsoft.HttpRepl/Program.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx

Resolves #151.
Previously, the `ui` command just tried to go to a url formed (essentially) from:
```C#
Uri uri = new Uri(baseAddress, swagger);
```
This was limited, for obvious reasons.
This PR adds flexibility in two ways:
1. The `ui` command now takes an optional parameter, where you can specify the absolute or relative (to the base address) swagger endpoint. So, for instance, if your base address is https://localhost:44366/ and your swagger endpoint is https://localhost:44366/mySwaggerEndpoint, you can issue either `ui mySwaggerEndpoint` or `ui https://localhost:44366/mySwaggerEndpoint` and it should launch the correct ui for you.
2. The `ui` command, absent a provided parameter, will attempt to use the `swagger.uiEndpoint` preference, if set, before falling back to the original …

Rework ui command to be more flexible

---

src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj

This PR changes the name of the assembly from `dotnet-httprepl` to `httprepl`. The effect here is that, once installed, the tool can be run by calling the more succinct `httprepl` instead of the more verbose `dotnet-httprepl`.
Note that by making this change we can no longer run the tool by calling `dotnet httprepl` (note the space). But since we already have a shortened way to do it, there's no harm there.
Also note that everything I said above refers to its usage as a global tool. If it's installed as a local tool, `dotnet-httprepl` (previously) and `httprepl` (with this PR) never worked anyway. Local tools require that you call it via the `dotnet` tool. In this case, `dotnet httprepl` still works.
cc @shanselman since you brought this up with me earlier

Renaming assembly from dotnet-httprepl to httprepl

---

src/Microsoft.HttpRepl/Commands/UICommand.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx

When we pulled #209 we forgot to include in-app documentation on the new flexibility of the `ui` command. This PR adds that documentation. 
The output will now be:
```console
Usage: ui [{swaggerUIAddress}]                                                                                          
Launches the Swagger UI page (if available) in the default browser
The ui command uses multiple sources to determine the swagger ui endpoint. In order of precedence:
1. The {swaggerUIAddress} parameter, if specified
2. The swagger.uiEndpoint preference, if set
3. A default url of [BaseAddress]/swagger
```
@scottaddie Thoughts on this? I figure this can be the basis for the changes to the docs once we settle on it here.

Adding in-app documentation for the ui command

---

eng/Versions.props
global.json
src/Microsoft.Repl/Microsoft.Repl.csproj

The changes needed to build the 3.0 release with the .net core 3.0 sdk. This probably won't build yet since the SDK pieces aren't on nuget yet.

Changes for 3.0 release.

---

eng/Versions.props

Setting up `master` to start building 3.1.0-preview-* builds going forward.
Attempting to straight this out based on the [Arcade versioning guidelines](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md). It recommends we do release-only, but we're not going that route at the moment. 
That part aside, we'll be leaving the `<PreReleaseVersionLabel>` value in the code, and when we need to release, we'll override it by setting `DotNetFinalVersionKind` to `release` in the build pipeline. 
This should mean we have all of our preview packages the same as they have been (e.g. 3.1.0-preview-XXXXX.X) and the release package will just drop the prerelease label, not change the `patch` version. 
Note that for 3.0-era patches, we'll need to continue the same …

Update version for 3.1 previews

---

azure-pipelines.yml

Changes the CI Trigger to:
- Include `release/*` branches (for instance, 3.0 bug fix releases branched from master)
- Exclude the `.md` files in the root that don't need to trigger a build
Changes the PR trigger to exclude the `.md` files in the root that don't need to trigger a build.
Includes are processed first, so we need to include all paths first, then exclude the couple of files we don't want. Just excluding them would mean it'd never get triggered. 
`release/*` is used rather than `rel/*` because the former is what is registered in the Maestro subscription.

Updating the YAML CI triggers

---

azure-pipelines.yml

Adding this parameter to fix the build errors, per https://github.com/dotnet/arcade/commit/df24cd9b34682b5509df5a08ef8a8952e5a4f623, https://github.com/dotnet/extensions/pull/3016 and https://github.com/dotnet/aspnetcore-tooling/pull/1622.

Add DotNetPublishUsingPipelines parameter

---

azure-pipelines.yml

Per https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/, we need to move off the `macOS-10.13` image to a newer one. `macOS-10.15` should be available, so we'll move to that.

Switching to the latest macOS image

---

CONTRIBUTING.md
README.md

For more details, see [PR16](https://github.com/dotnet/org-policy/blob/master/doc/PR16.md).

Fix links to Code of Conduct

---

src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj

Resolves #348 - removes netcoreapp3.0 since it is EOL and adds netcoreapp3.1 (LTS).

Drop netcoreapp3.0, add netcoreapp3.1

---

build/PackageVersions.targets
src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj
src/Microsoft.HttpRepl/Program.cs

Addresses #238 by adding a reference to the `System.Text.Encoding.CodePages` package and registering the included `CodePagesEncodingProvider` instance. This makes Windows-1252 and other Codepage encodings available for handling responses.

Add support for other encodings

---

src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs
src/Microsoft.HttpRepl/Suggestions/HeaderCompletion.cs
src/Microsoft.HttpRepl/WellKnownHeaders.cs
test/Microsoft.HttpRepl.Tests/Commands/PostCommandTests.cs

Fixes #237.
There were actually two separate things going on:
1. As pointed out by #237, almost all headers were duplicated if you were doing anything with a request body (because headers were being set for both the request and the content).
2. The fix in #277 showed the other part of it - that Content-Type specifically was always being duplicated (with or without a request body) if it was added with `set header` or the `--header` argument, because it was special-cased and set early before all those were added in bulk.
This PR addresses both issues, and supersedes #277, which I'll close with an explanation once this goes in.

Don't duplicate headers

---

src/Microsoft.HttpRepl/ApiConnection.cs

Currently, the search paths used to automatically find the OpenAPI description are hard-coded in a pipe-delimited string on one line of code. This makes submitting a PR to add another entry to it unnecessarily annoying to a contributor. This PR changes the way we handle that to make such PRs a little easier. #360 will further address the preferences portion of the search paths at a later date.

Make it easier to submit OpenAPI Description search path PRs

---

src/Microsoft.Repl/Parsing/CoreParser.cs
test/Microsoft.Repl.Tests/Parsing/CoreParseResultTests.cs

Fixes #365 
This is a short-term quick fix to try to sneak it into 3.1 while we work on the new parsing in 5.0. Will cherry-pick to release/3.1 once approved.

Fix issue with extra spaces in commands

---

src/Microsoft.Repl/Input/KeyHandlers.cs
src/Microsoft.Repl/Microsoft.Repl.csproj

Fixes #374.
Prior to this fix, pressing the Windows key (or the application key) could cause you to get a null character (`\0`) in the input buffer. Depending on where this landed in the command you pasted (usually at the end), it could break command parsing. So here we just make sure those three keys are "handled" by using the Unhandled delegate.
Those keys were not available on the `ConsoleKey` enum in the original target of netstandard1.3. After discussions with @bradygaster about which targets were reasonable, we went ahead and moved to netstandard2.0 rather than hardcoding the values.

"Handle" special windows keyboard keys

---

src/Microsoft.HttpRepl/Commands/ConnectCommand.cs
src/Microsoft.HttpRepl/Preferences/WellKnownPreference.cs
test/Microsoft.HttpRepl.Tests/Commands/CommandTestsBase.cs
test/Microsoft.HttpRepl.Tests/Commands/ConnectCommandTests.cs

As of .NET 5 RC1, the `dotnet new webapi` template now has a default start url of `swagger`. Because the default Swashbuckle-generated OpenAPI description doesn't contain a Servers element, this will put HttpRepl users that launch from VS/VS Code into a pit of failure by having a base address of `https://localhost:{port}/swagger/`, even though the API is, by default, based at the root. The user won't be able to navigate their API at all, because you can't navigate "above" the base address.
Since it is unlikely a user would put their API inside the `/swagger` path, we will special-case this scenario and remove that from the url. We will give the user an escape hatch via the preference if they do put their API under that path.

Fixup /swagger root urls

---

global.json

Updating the .NET SDK used for building to RC1 (5.0.100-rc.1.20452.10). See https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-1/ for details on changes.

Update to .NET 5 RC1

---

global.json

Updating global.json to target .NET 5 RC2 released today.

Update .NET 5 to RC2

---

azure-pipelines.yml

The arcade build scripts include a step to publish the xunit test results, so we don't need that in our definition. Also cleaned up a few references to the old repo location (aspnet/httprepl).

Clean up build definition

---

src/Microsoft.HttpRepl/Preferences/WellKnownPreference.cs
src/Microsoft.HttpRepl/Program.cs

Resolves #305.
Introduces a new setting - `httpClient.proxy.useDefaultCredentials` - that, if set, will configure the tool's HttpClient to use the default credentials for authenticating with the system default proxy.

Add preference for using default credentials with proxy

---

src/Microsoft.HttpRepl/Commands/PrefCommand.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx
test/Microsoft.HttpRepl.Tests/Commands/PrefCommandTests.cs

Resolves #310 
Since, at this point, we don't want to override the user's settings automatically, for now we will just present a warning if we think they are setting their default editor to VS Code. The warning guides them to set the proper command arguments.

Warn about command arguments when using VS Code

---

src/Microsoft.HttpRepl/Commands/HelpCommand.cs
src/Microsoft.HttpRepl/Commands/ListCommand.cs
src/Microsoft.HttpRepl/Program.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx
src/Microsoft.Repl/Commanding/DefaultCommandInput.cs
test/Microsoft.HttpRepl.Tests/Commands/HelpCommandTests.cs
test/Microsoft.HttpRepl.Tests/Commands/ListCommandTests.cs

Resolves #70 by moving the form of the help command that gave details about a particular route out of `help` and into a verbose variant of the list command (`ls --verbose` or `dir --verbose`).
Along the way, also resolves #409 since that prevented this from working as well and resolves #410 since that became immediately apparent once #409 was fixed.

Move request details from help to verbose list command

---

azure-pipelines.yml

A couple of small build tweaks here:
- Arcade updated their scripts so you can configure it to only publish the xunit test results and not the trx test results. We just need to swap out `enablePublishTestResults: true` (which will publish both) for `testResultsFormat: xunit` (which will only publish xunit results. This will get rid of the build warnings we had (one per platform per configuration)
- The `enablePublishUsingPipelines: true` parameter wasn't needed for what we're doing in our builds
- We were publishing the log files twice under slightly different container names - once in our build steps and then again in the Arcade templates.

Remove unused steps from build process

---

.editorconfig
build/PackageVersions.targets
src/Microsoft.HttpRepl.Telemetry/Telemetry.cs
src/Microsoft.HttpRepl.Telemetry/UserLevelCacheWriter.cs
src/Microsoft.HttpRepl/ApiConnection.cs
src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs
src/Microsoft.HttpRepl/Commands/ClearCommand.cs
src/Microsoft.HttpRepl/Commands/ConnectCommand.cs
src/Microsoft.HttpRepl/Commands/HelpCommand.cs
src/Microsoft.HttpRepl/Commands/RunCommand.cs
src/Microsoft.HttpRepl/Commands/SetHeaderCommand.cs
src/Microsoft.HttpRepl/Commands/UICommand.cs
src/Microsoft.HttpRepl/FileSystem/RealFileSystem.cs
src/Microsoft.HttpRepl/HttpState.cs
src/Microsoft.HttpRepl/Preferences/UserFolderPreferences.cs
src/Microsoft.HttpRepl/Program.cs
src/Microsoft.HttpRepl/Suggestions/HeaderCompletion.cs
src/Microsoft.Repl/ConsoleHandling/AnsiColorExtensions.cs
src/Microsoft.Repl/ConsoleHandling/ConsoleManager.cs
src/Microsoft.Repl/ConsoleHandling/Reporter.cs
src/Microsoft.Repl/Input/InputManager.cs
test/Microsoft.HttpRepl.Tests/Commands/ChangeDirectoryCommandTests.cs
test/Microsoft.HttpRepl.Tests/Commands/CommandTestsBase.cs
test/Microsoft.HttpRepl.Tests/Commands/PostCommandTests.cs
test/Microsoft.HttpRepl.Tests/Commands/PrefCommandTests.cs
test/Microsoft.HttpRepl.Tests/Commands/SetHeaderCommandTests.cs
test/Microsoft.HttpRepl.Tests/Commands/UICommandTests.cs
test/Microsoft.HttpRepl.Tests/HttpStateTests.cs
test/Microsoft.HttpRepl.Tests/Suggestions/HeaderCompletionTests.cs
test/Microsoft.HttpRepl.Tests/Suggestions/ServerPathCompletionTests.cs

Resolves #413, fixes a bunch of warnings/suggestions (I mostly skipped the test and telemetry projects for now) and also switches the .editorconfig var setting to suggest the explicit type name rather than suggesting var.
Added #418 to track one error that I wasn't positive about how to fix at the moment, but didn't want to block the rest of this.

Update Analyzers to 3.3 and disable var

---

src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs
src/Microsoft.Repl/Resources/Strings.Designer.cs
src/Microsoft.Repl/Resources/Strings.resx

Resolves #304.
Handle some of the "expected" exceptions in `BaseHttpCommand` when executing HTTP Requests via `HttpClient`.

Handle HTTP Request errors in BaseHttpCommand

---

src/Microsoft.HttpRepl/ApiConnection.cs
src/Microsoft.HttpRepl/OpenApi/IOpenApiSearchPathsProvider.cs
src/Microsoft.HttpRepl/Preferences/OpenApiSearchPathsProvider.cs
src/Microsoft.HttpRepl/Preferences/WellKnownPreference.cs
test/Microsoft.HttpRepl.Fakes/FakePreferences.cs
test/Microsoft.HttpRepl.Tests/Preferences/OpenApiSearchPathsProviderTests.cs

Resolves #360. 
Adds two additional preferences:
- `swagger.addToSearchPaths` (adds the specified paths to the default list)
- `swagger.removeFromSearchPaths` (removes the specified paths from the default list if they exist)
and configures the original available preference (`swagger.searchPaths`) to override both the default list _and_ the two new preferences.

Add more preferences for configuring openapi search paths

---

src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx
src/Microsoft.Repl/Parsing/CoreParser.cs
test/Microsoft.HttpRepl.Tests/Commands/GetCommandTests.cs
test/Microsoft.Repl.Tests/Parsing/CoreParseResultTests.cs

Resolves #426.
Also fixed a bug in the parser where it didn't handle quoted sections that didn't have spaces in them. The fix is maybe not a complete fix, but I didn't think it was worth going further since we have the `System.CommandLine` work coming up that will hopefully replace the entire parser.

Remove --response option from HTTP commands

---

src/Microsoft.HttpRepl/ApiConnection.cs
src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs
src/Microsoft.HttpRepl/Commands/ConnectCommand.cs
src/Microsoft.HttpRepl/Commands/ListCommand.cs
src/Microsoft.HttpRepl/OpenApi/ApiDefinitionParseResult.cs
src/Microsoft.HttpRepl/OpenApi/ApiDefinitionReader.cs
src/Microsoft.HttpRepl/OpenApi/IApiDefinitionReader.cs
src/Microsoft.HttpRepl/OpenApi/OpenApiDotNetApiDefinitionReader.cs
src/Microsoft.HttpRepl/Resources/Strings.Designer.cs
src/Microsoft.HttpRepl/Resources/Strings.resx
test/Microsoft.HttpRepl.Fakes/ApiDefinitionReaderStub.cs
test/Microsoft.HttpRepl.Tests/OpenApi/ApiDefinitionReaderTests.cs
test/Microsoft.HttpRepl.Tests/OpenApi/OpenApiDotNetApiDefinitionReaderTests.cs
test/Microsoft.HttpRepl.Tests/OpenApi/OpenApiDotNetApiDefinitionReaderV2Tests.cs
test/Microsoft.HttpRepl.Tests/OpenApi/OpenApiDotNetApiDefinitionReaderV3Tests.cs

Resolves #406 
https://github.com/microsoft/OpenAPI.NET provides us with validation messages when it parses an OpenAPI Description. This PR includes those messages in the `--verbose` output of the `connect` command.
Along the way, it also refactors the IApiDefinitionReader definition to handle more information (the above validation messages) and adds some formatting/color to the verbose output.

OpenAPI validation during connect

---

src/Microsoft.HttpRepl/Program.cs

Leftover usage of `dotnet httprepl` instead of just `httprepl`

Remove usage of `dotnet httprepl`

---

build/PackageVersions.targets
global.json

Updates the repo to use the .NET 5 RTM SDK and updates all references to their latest.
Resolves #428 
Resolves #431

Update SDK to 5.0 RTM and update other references

---

README.md
TELEMETRY.md

Delete the *TELEMETRY.md* file and move its docs link to the relevant section of the *README* file.

More telemetry doc cleanup

---

src/Microsoft.Repl/Commanding/DefaultCommandDispatcher.cs
src/Microsoft.Repl/ConsoleHandling/ConsoleManager.cs
src/Microsoft.Repl/ConsoleHandling/IConsoleManager.cs
src/Microsoft.Repl/ConsoleHandling/Writable.cs
src/Microsoft.Repl/IShellState.cs
src/Microsoft.Repl/Input/IInputManager.cs
src/Microsoft.Repl/Input/InputManager.cs
src/Microsoft.Repl/Input/KeyHandlers.cs
src/Microsoft.Repl/Scripting/ScriptExecutor.cs
src/Microsoft.Repl/ShellState.cs
src/Microsoft.Repl/Suggestions/SuggestionManager.cs
test/Microsoft.HttpRepl.Fakes/LoggingConsoleManagerDecorator.cs
test/Microsoft.HttpRepl.Fakes/MockConsoleManager.cs
test/Microsoft.HttpRepl.Fakes/MockInputManager.cs
test/Microsoft.HttpRepl.Fakes/MockedShellState.cs
test/Microsoft.Repl.Tests/ShellTests.cs

Fixes #443.
See https://github.com/dotnet/HttpRepl/issues/443#issuecomment-728789788 for details on the specific problems in HttpRepl and  https://github.com/microsoft/terminal/issues/8312 for some background on why the issues show up differently (or not at all) in different terminals.
Essentially, HttpRepl tied the caret position on the input buffer to the caret position of the console window in a way that causes problems in virtual terminals (e.g. Windows Terminal). Not all terminals were impacted the same way, though all variants other than vanilla cmd.exe had problems.
To fix this, we "disconnect" the cursor position in the console window from the cursor position in the input buffer, but still move them together when appropriate. The concept of the `CaretPosition` is moved from the …

Fix console errors

---

src/Microsoft.Repl/Commanding/DefaultCommandDispatcher.cs
src/Microsoft.Repl/ConsoleHandling/ConsoleManager.cs
src/Microsoft.Repl/ConsoleHandling/IConsoleManager.cs
src/Microsoft.Repl/ConsoleHandling/Writable.cs
src/Microsoft.Repl/IShellState.cs
src/Microsoft.Repl/Input/IInputManager.cs
src/Microsoft.Repl/Input/InputManager.cs
src/Microsoft.Repl/Input/KeyHandlers.cs
src/Microsoft.Repl/Scripting/ScriptExecutor.cs
src/Microsoft.Repl/ShellState.cs
src/Microsoft.Repl/Suggestions/SuggestionManager.cs
test/Microsoft.HttpRepl.Fakes/LoggingConsoleManagerDecorator.cs
test/Microsoft.HttpRepl.Fakes/MockConsoleManager.cs
test/Microsoft.HttpRepl.Fakes/MockInputManager.cs
test/Microsoft.HttpRepl.Fakes/MockedShellState.cs
test/Microsoft.Repl.Tests/ShellTests.cs

This cherry picks the console errors fix that we just pushed out in 5.0.1.

Cherry Pick: Fix console errors (#457)

---

src/Microsoft.Repl/Input/InputManager.cs

It looks like this got missed in #457 when addressing #443. 
Essentially, when "inserting" into existing text on the console, we have to write back out the rest of the string (so that it "moves forward" with the insertion). #457's refactoring missed that the console's cursor position needed to be moved back after the Write call. Rather than moving it back completely and then moving it forward again (with the input cursor), we just move it back one less than the length.

Fix improper handling of text insertion

---

src/Microsoft.Repl/Input/InputManager.cs
src/Microsoft.Repl/Properties/AssemblyInfo.cs
test/Microsoft.HttpRepl.Fakes/MockedShellState.cs
test/Microsoft.Repl.Tests/InputManagerTests.cs

Another piece of the puzzle to go along with #457 and #470 when addressing #443.
In this case, some of the caret position moving code that was removed during the refactor in #457 was never put back in. This PR adds it back in, and adds some tests for these specific scenarios. The tests only cover the input side, not the console side (because we don't have a good abstraction for the console) but the input side was broken as well.

Fix console issues with deleting characters

---

src/Microsoft.Repl/Input/InputManager.cs
test/Microsoft.Repl.Tests/ShellTests.cs

Resolves #472
This handles a specific case of #119 where the unprintable character coming through is the null character. This seems common enough (perhaps the most common of the scenarios highlighted by #119) to handle on its own.

Drop null character-causing keystrokes

---

azure-pipelines.yml

ubuntu-16.04 was removed recently (https://github.com/actions/virtual-environments/issues/3287), bumping to 20.04.

Use non-deprecated Azure Pipelines Ubuntu pool

---

global.json

With .NET 6 releasing today, going ahead and updating to use the RTM SDK.

Update to .NET 6 RTM

---

eng/Versions.props

Updating the version of the product to 6.0. Partially this is to match the SDK (#530) but also because we're dropping support for 2.1 which ended back in August. Since that's a big breaking change, the version bump is reasonable even if there aren't new features since 5.0.

Update version to 6.0

---

src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj

System.Private.Uri has a number of CVEs for version 4.3.0. We already specified 4.3.2 in the `Directory.Packages.props` file, but since it wasn't directly referenced by any projects it wasn't fixing the issue. This PR adds the reference to the affected project.

Fix System.Private.Uri CG Alerts

---

src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj

.NET 5.0 reached [end of support](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) last month, so we'll remove it as a target framework.

Remove .NET 5.0 as it is out of support

---

Directory.Packages.props

To ensure we're still getting telemetry, we need to update to the latest AppInsights SDK. Will need to backport this to the 6.0 branch as well.

Update AppInsights to latest release version

---

Directory.Packages.props

Updating AppInsights for continued data ingestion on latest release, similar to #563

Update AppInsights to 2.20.0 for release/6.0.1

---

Directory.Packages.props

Updating Swashbuckle.AspNetCore to latest to get past a component governance alert

Update Swashbuckle.AspNetCore to latest

---

src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj

Have a CG alert because Microsoft.HttpRepl is building with an old version of Newtonsoft.Json. Our direct references pull in something newer in other places and we ship the newer one, but this package still builds this way so we need to correct it.

Fix CG alert with Newtonsoft

---

Directory.Packages.props
src/Microsoft.HttpRepl.Telemetry/Telemetry.cs

2.20 is deprecated, so we need to update.

Update AppInsights to latest version

---

test/Microsoft.HttpRepl.Tests/Commands/CommandTestsBase.cs

Hi! Thank you for this tool! ;)
I read code and found duplicate null check. As you can see, [this](https://github.com/dotnet/HttpRepl/blob/main/test/Microsoft.HttpRepl.Tests/Commands/CommandTestsBase.cs#L125) null check is useless, because [here](https://github.com/dotnet/HttpRepl/blob/main/test/Microsoft.HttpRepl.Tests/Commands/CommandTestsBase.cs#L121) we already check path by null
Hope my changes make your code better ;)

Delete useless null check for CommandTestsBase

---

eng/Versions.props
global.json

With the .NET 8 release today, updating the SDK required to the released 8.0.100 and updating the version number to 8.0.0

Update to .NET8 GA, Update version to 8.0-preview

---

azure-pipelines-pr.yml

This is step 1 of prep work for 1ES/MicroBuild pipeline template migration. Simply creates a new separate definition that runs only for PR builds on dnceng-public.

Split PR pipeline

---

azure-pipelines.yml

Following on #637 this is step 2 of preparation for template migration. Doesn't actually move the official build to the new templates, but sets things up better for it, including dropping the linux/mac builds since those don't produce any assets currently.

Update official pipeline definition

---

azure-pipelines.yml

CodeSignValidation is flagging our bin folder artifact, which is just the copy of all of our pre-signed binaries that we create for testing/validation purposes and is not shipped (we only ship the full nuget package, which is signed, as are its contents). This adds an exclusion for that folder so that it doesn't fail the build.

Add CSV exclusion

---

eng/Versions.props
src/Microsoft.HttpRepl.Telemetry/Microsoft.HttpRepl.Telemetry.csproj
src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj
src/Microsoft.Repl/Microsoft.Repl.csproj

Dropping net6/net7 builds from the nuget package as they're out of support (or will be by the time we ship this in a stable build).
net7.0 is out of support as of May 14, 2024
net6.0 will be going out of support on November 12, 2024
Bumping the version to 8.1 rather than just 8.0.1 since this is a breaking change for anyone trying to run it on those runtimes.

Remove net6.0 and net7.0 versions from shipping packages
